#!/bin/sh

python write_dataset.py

rm ../input/dataset/*.keras
rm result.log

for i in {1..3}:
do
    python train.py 1 0
    python check.py 1 >> result.log

    python train.py 2 0
    python check.py 2 >> result.log

    python train.py 3 0
    python check.py 3 >> result.log

    python train.py 4 0
    python check.py 4 >> result.log
done
